3. Revisit the matmult.py example from yesterday and improve its performance using Numpy.

In [3]:
import numpy as np

def mat_mult(N):
    # Generate random matrices
    X = np.random.randint(0, 100, (N, N))
    Y = np.random.randint(0, 100, (N, N + 1))
    
    # Matrix multiplication
    result = np.dot(X, Y)
    return result

N = 250
result = mat_mult(N)
print(result)

[[644573 639487 595093 ... 616357 668578 612211]
 [605925 610807 575754 ... 564803 638847 607196]
 [632048 628440 611944 ... 593809 650891 621690]
 ...
 [603667 630364 609350 ... 601280 661338 596240]
 [641565 639275 611087 ... 584072 680642 614673]
 [661541 659412 637983 ... 620670 702126 655501]]
