In [2]:
import numpy as np

a. Create a null vector of size 10 but the fifth value which is 1

In [5]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


b. Create a vector with values ranging from 10 to 49

In [8]:
b = np.arange(10, 50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


c. Reverse a vector (first element becomes last)

In [11]:
c = np.arange(10)
print('Original vector is: ', c)
c_rev = c[::-1]
c_rev
print('Reversed vector is: ', c_rev)

Original vector is:  [0 1 2 3 4 5 6 7 8 9]
Reversed vector is:  [9 8 7 6 5 4 3 2 1 0]


d. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
d = np.arange(9)
d = d.reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:
e = np.array([1,2,0,0,4,0])
e_ind = e > 0
print(e_ind)

[ True  True False False  True False]


f. Create a random vector of size 30 and find the mean value

In [20]:
f = np.random.random((30))
f_mean = np.mean(f)
print(f_mean)

0.44875455427540334


g. Create a 2d array with 1 on the border and 0 inside

In [23]:
g = np.zeros((4, 4),dtype=int)
g[0,:] = 1
g[-1,:] = 1
g[:,0] = 1
g[:,-1] = 1
print(g)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [26]:
h = np.zeros((8, 8),dtype=int)
h[1::2, ::2] = 1 
h[::2, 1::2] = 1
print(h)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


i. Create a checkerboard 8x8 matrix using the tile function

In [29]:
i = np.array([[0,1],[1,0]],dtype=int)
i = np.tile(i,(4,4))
print(i)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [32]:
j = np.arange(11)
j[3:9:1] = -j[3:9:1]
print(j)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


k. Create a random vector of size 10 and sort it

In [35]:
k = np.random.random(10)
k = np.sort(k)
print(k)

[0.22239791 0.31600646 0.63365347 0.64029194 0.66372695 0.82103969
 0.82786403 0.9259955  0.93865657 0.96188809]


l. Consider two random array A anb B, check if they are equal

In [38]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = B == A
print(equal)

[False  True False False  True]


m. How to calculate the square of every number in an array in place (without creating temporaries)?

In [41]:
m = np.arange(10, dtype=np.int32)
print(m.dtype)
print(m)
m = np.square(m)
print(m.dtype)
print(m)

int32
[0 1 2 3 4 5 6 7 8 9]
int32
[ 0  1  4  9 16 25 36 49 64 81]


n. How to get the diagonal of a dot product?

In [44]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diagonal(C)
print('C = ', C)
print('Diagonal = ', D)

C =  [[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
Diagonal =  [ 18  66 132]
